name: Pre-Release

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: read

jobs:
  TagAndPublish:
    name: Tag and Publish
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Full History
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.1.0

      - name: Calculate Version
        id: version
        uses: gittools/actions/gitversion/execute@v4.1.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test -- --coverage

      - name: Tag Commit
        uses: fgrzl/actions/tag-commit@v0.0.4
        with:
          tag: ${{ steps.version.outputs.semVer }}

      - name: Publish NPM
        uses: fgrzl/actions/publish-npm@v0.0.4
        with:
          npm-token: ${{ secrets.NPM_TOKEN  }}
          label: ${{ steps.version.outputs.PreReleaseLabel }}
          version: ${{ steps.version.outputs.semVer }}

      - name: Prune Pre-release Tags
        uses: fgrzl/actions/prune-tags@v0.0.4
