name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v5
        with:
          ref: develop
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run format
        run: npm run format

      - name: Run tests
        run: npm run test:coverage

      - name: Run linting
        run: npm run lint:check

      - name: Build project
        run: npm run build

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.1.0

      - name: Determine Version with GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v4.1.0

      - name: Merge to main
        run: |
          git checkout main
          git pull origin main
          git merge --no-ff develop -m "Release v${{ steps.gitversion.outputs.majorMinorPatch }}"
          git push origin main

      - name: Create Git tag
        run: |
          git tag -a v${{ steps.gitversion.outputs.majorMinorPatch }} -m "Release v${{ steps.gitversion.outputs.majorMinorPatch }}"
          git push origin v${{ steps.gitversion.outputs.majorMinorPatch }}

      - name: Merge back to develop
        run: |
          git checkout develop
          git pull origin develop
          git merge --no-ff main -m "Merge main back to develop after release v${{ steps.gitversion.outputs.majorMinorPatch }}"
          git push origin develop
